import './js/js-refs';
import './js/scroll-to-up';
import './js/modal-order-now';
import './js/popular-recipe';
import './js/header-mobile-menu';
import './js/js-popular';
import './js/js-categories';
import './js/favorites-page';
import './js/hero';